# The Python Programming Language

add the number is a function that takes and add them together

In [3]:
def add(x,y):
    return x+y
add(4,5)

9

add_numbers updated to take an optional 3rd parameter. Using print allows printing of multiple expressions within a single cell.

In [9]:
def add_number(x,y,z=None):
    if (z==None):
        return x+y
    else:
        return x+y+z
add_number(4,5,8)

17

add_numbers updated to take an optional flag parameter.

In [13]:
 def add_number(x,y,z=None,flag=False):
        if(flag):
            print('Flag is true')
        if(z==None):
            return(x+y)
        else:
            return (x+y+z)
print(add_number(1,2,3,flag=True))

Flag is true
6


Assign function add_numbers to variable a.

In [14]:
def add_number(x,y):
    return x+y
a=add_number
a(1,2)

3

# The Python Programming Language: Types and Sequences

Use type to return the object's type.

In [15]:
type("Hello World")

str

In [16]:
type(None)

NoneType

In [17]:
type(15)

int

In [18]:
type(add_number)

function

In [19]:
type(1.5)

float

Tuples are an immutable data structure (cannot be altered).

In [20]:
x=(1,'a',2,'b')
type(x)

tuple

Lists are a mutable data structure.

In [21]:
x=[1,'a',2,'h']
type(x)

list

Use append to append an object to a list.

In [24]:
x.append(5)
x

[1, 'a', 2, 'h', 5, 5, 5]

This is an example of how to loop through each item in the list.

In [25]:
for item in x:
    print(item)

1
a
2
h
5
5
5


Or using the indexing operator:

In [28]:
i=0
while(i != len(x)):
    print(x[i])
    i=i+1

1
a
2
h
5
5
5


Use + to concatenate lists.

In [29]:
[4,5] + [5,7]

[4, 5, 5, 7]

Use * to repeat

In [30]:
[2]*2

[2, 2]

Use the in operator to check if something is inside a list.

In [32]:
1 in [2,4,6,6,1]

True

Now let's look at strings. Use bracket notation to slice a string.

In [34]:
x='This is a String'
print(x[0])
print(x[0:1])
print(x[0:2])
print(x[-1])

T
T
Th
g


This will return the slice starting from the 4th element from the end and stopping before the 2nd element from the end.

In [36]:
x[-4:-2]

'ri'

In [47]:
first_name='Vishal'
Last_Name='Upadhyay'
print(first_name+' '+Last_Name)
print(first_name* 3)
print('Vishal' in first_name)

Vishal Upadhyay
VishalVishalVishal
True


split returns a list of all the words in a string, or a list split on a specific character.

In [49]:
first_name= 'Christoper Arthur Hansen Brooks'.split(' ')[0]
second_name='Chrishtoper Arthur Hansen Brooks'.split(' ')[-1]
print(first_name)
print(second_name)

Christoper
Brooks


Dictionaries associate keys with values.

In [52]:
x= {'Chrishtoper Brooks':'brooksch@umich.edu','Bill Gates':'billg@microsoft.com'}
x

{'Chrishtoper Brooks': 'brooksch@umich.edu',
 'Bill Gates': 'billg@microsoft.com'}

In [53]:
x['Chrishtoper Brooks']

'brooksch@umich.edu'

In [55]:
x['Kevyn Collins-Thompson']=None

In [56]:
x

{'Chrishtoper Brooks': 'brooksch@umich.edu',
 'Bill Gates': 'billg@microsoft.com',
 'Kevyn Collins-Thompson': None}

Iterate over all of the keys:

In [58]:
for item in x:
    print(x[item])

brooksch@umich.edu
billg@microsoft.com
None


iterate over all of the values:

In [63]:
for  email in x.values():
    print(email)

brooksch@umich.edu
billg@microsoft.com
None


iterate over all of the items in the list:

In [64]:
for name,email in x.items():
    print(name)
    print(email)

Chrishtoper Brooks
brooksch@umich.edu
Bill Gates
billg@microsoft.com
Kevyn Collins-Thompson
None


# The Python Programming Language: More on Strings

In [66]:
print('Chris' + str(2))

Chris2


Python has a built in method for convenient string formatting.

In [70]:
sales_record= {
    'price':3.24,
    'num_items':4,
    'person':"Chris"
    }
print('{} Bought {} items(s) at a price of {} each for a total of {} '.format(sales_record['person'],sales_record['price'],sales_record['num_items'],sales_record['num_items']*sales_record['price']))

Chris Bought 3.24 items(s) at a price of 4 each for a total of 12.96 


# Reading and Writing CSV files

In [85]:
import pandas as pd
mpg=pd.read_excel(r'C:\Users\Lenovo\Desktop\DATA SETS\Cars\Cars.xlsx')
mpg.head()

manufacturer model  displ  year  cyl       trans  cty  hwy fl    class
0         audi    a4    1.8  1999    4    auto(l5)   18   29  p  compact
1         audi    a4    1.8  1999    4  manual(m5)   21   29  p  compact
2         audi    a4    2.0  2008    4  manual(m6)   20   31  p  compact
3         audi    a4    2.0  2008    4    auto(av)   21   30  p  compact
4         audi    a4    2.8  1999    6    auto(l5)   16   26  p  compact

In [88]:
import csv
%precision 2
with open('Cars.csv') as csvfile:
    mpg=list(csv.DictReader(csvfile))
mpg[:3]

[OrderedDict([('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'auto(l5)'),
              ('cty', '18'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'manual(m5)'),
              ('cty', '21'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '2'),
              ('year', '2008'),
              ('cyl', '4'),
              ('trans', 'manual(m6)'),
              ('cty', '20'),
              ('hwy', '31'),
              ('fl', 'p'),
              ('class', 'compact')])]

In [89]:
len(mpg)

234

In [90]:
mpg[0].keys()

odict_keys(['manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'cty', 'hwy', 'fl', 'class'])

This is how to find the average cty fuel economy across all cars. All values in the dictionaries are strings, so we need to convert to float.

In [91]:
sum(float(d['cty']) for d in mpg)/len(mpg)

16.86

Similarly this is how to find the average hwy fuel economy across all cars.

In [92]:
sum(float(d['hwy']) for d in mpg)/len(mpg)

23.44

Use set to return the unique values for the number of cylinders the cars in our dataset have.

In [93]:
cylinders=set(d['cyl'] for d in mpg)
cylinders

{'4', '5', '6', '8'}

Here's a more complex example where we are grouping the cars by number of cylinder, and finding the average cty mpg for each group

In [104]:
ctyMPgbycyl=[]
for c in cylinders:
    summpg=0
    cylcount=0
    for d in mpg:
        if d['cyl'] == c:
            summpg+=float(d['cty'])
            cylcount+=1
    ctyMPgbycyl.append((c,summpg/cylcount))  #append the tuple('cylinder','avg mpg')
    
ctyMPgbycyl.sort(key=lambda x: x[0])v
ctyMPgbycyl

[('4', 21.01), ('5', 20.50), ('6', 16.22), ('8', 12.57)]

And here's an example of how to find the average hwy mpg for each class of vehicle in our dataset.

In [110]:
vehicleclass = set(d['class'] for d in mpg) # what are the class types
vehicleclass

{'2seater', 'compact', 'midsize', 'minivan', 'pickup', 'subcompact', 'suv'}

In [116]:
HwyMPgbyclass=[]
for t in vehicleclass:
    summpg=0
    vclasscount=0
    for d in mpg:
        if d['class']==t:
            summpg+=float(d['hwy'])
            vclasscount+=1
    HwyMPgbyclass.append((t,summpg/vclasscount))
HwyMPgbyclass.sort(key=lambda x:x[1])
HwyMPgbyclass

[('pickup', 16.88),
 ('suv', 18.13),
 ('minivan', 22.36),
 ('2seater', 24.80),
 ('midsize', 27.29),
 ('subcompact', 28.14),
 ('compact', 28.30)]

An example of a class in python:

In [119]:
class Person:
    department = "School of Information"
    
    def set_name(self,new_name):
        self.name=new_name
    def set_location(self,location):
        self.location=location

In [122]:
person=Person()
person.set_name("Vishal")
person.set_location("Indore")
print("{} live in {} and works in the department {} ".format(person.name,person.location,person.department))

Vishal live in Indore and works in the department School of Information 


Here's an example of mapping the min function between two lists.

In [125]:
store1=[10.00,11.00,12.34,2.34]
store2=[9.00,11.10,12.54,2.02]
cheapest=map(min,store1,store2)
cheapest

Now let's iterate through the map object to see the values.

In [126]:
for i in cheapest:
    print(i)

9.0
11.0
12.34
2.02


# The Python Programming Language: Lambda and List Comprehensions

In [129]:
my_function = lambda a,b,c:a+b+c
my_function(1,21,5)

27

Let's iterate from 0 to 999 and return the even numbers.

In [133]:
my_list=[]
for number in range (0,1000):
    if number % 2 ==0:
            my_list.append(number)
my_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

Now the same thing but with list comprehension.

In [134]:
my_list =[number for number in range(0,1000) if number % 2 == 0]
my_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

# The Python Programming Language: Numerical Python (NumPy)¶

In [135]:
import numpy as np

# Creating Arrays

Create a list and convert it to a numpy array

In [136]:
my_list=[1,2,5,6]
x=np.array(my_list)
x

array([1, 2, 5, 6])

Or just pass in a list directly

In [137]:
y=np.array([5,7,6,3])
y

array([5, 7, 6, 3])

Pass in a list of lists to create a multidimensional array.

In [139]:
z=np.array([[5,7,9,0],[4,6,3,7],[4,1,3,9]])
z

array([[5, 7, 9, 0],
       [4, 6, 3, 7],
       [4, 1, 3, 9]])

Use the shape method to find the dimensions of the array. (rows, columns)

In [140]:
z.shape

(3, 4)

arange returns evenly spaced values within a given interval.

In [142]:
n=np.arange(0,30,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

reshape returns an array with the same data with a new shape.

In [144]:
n=n.reshape(5,3)
n

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

linspace returns evenly spaced numbers over a specified interval

In [149]:
o = np.linspace(0,4,9)
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [150]:
o.resize(3,3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [152]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [153]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [154]:
np.diag(y)

array([[5, 0, 0, 0],
       [0, 7, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 3]])

Create an array using repeating list (or see np.tile)

In [155]:
np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [156]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])





Combining Arrays

In [157]:
p = np.ones([2,3],int)
p

array([[1, 1, 1],
       [1, 1, 1]])

Use vstack to stack arrays in sequence vertically (row wise).

In [165]:
np.vstack([p,2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [166]:
np.hstack([p,2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

# Operations

Use +, -, *, / and ** to perform element wise addition, subtraction, multiplication, division and power.

In [167]:
x.dot(y)

67

In [168]:
z=np.array([y,y**2])
print(len(z))

2


In [169]:
z.shape

(2, 4)

In [170]:
z.T

array([[ 5, 25],
       [ 7, 49],
       [ 6, 36],
       [ 3,  9]])

In [171]:
z = z.astype('f')
z.dtype

dtype('float32')

# Math Functions

Numpy has many built in math functions that can be performed on arrays.

In [172]:
a=np.array([-4,-2,1,3,5])
a

array([-4, -2,  1,  3,  5])

In [173]:
a.sum()

3

In [174]:
a.mean()

0.6

In [175]:
a.std()

3.2619012860600183

In [176]:
a.var()

10.64

In [177]:
a.min()

-4

In [178]:
a.max()

5

In [179]:
a.argmax() #Index Dega OK!

4

In [180]:
a.argmin()

0

# Indexing / Slicing

In [181]:
s= np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

In [182]:
s[0],s[1],s[-1]

(0, 1, 144)

In [183]:
s[1:5]

array([ 1,  4,  9, 16], dtype=int32)

In [184]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [185]:
r[2:2]

array([], shape=(0, 6), dtype=int32)

In [186]:
r[3, 3:6]

array([21, 22, 23])

In [187]:
r[r > 30]

array([31, 32, 33, 34, 35])

In [188]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

# Copying Data


Be careful with copying and modifying arrays in NumPy!

In [189]:
r2=r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [190]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [191]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

r has also been changed!

In [193]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [194]:
r_copy[:] = 10
print(r_copy, '\n')
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] 

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


# Iterating Over Arrays

Let's create a new 4 by 3 array of random numbers 0-9.

In [196]:
test=np.random.randint(0,10,(4,3))
test

array([[4, 7, 0],
       [9, 2, 7],
       [3, 5, 8],
       [8, 5, 3]])

In [197]:
for row in test:
    print(row)

[4 7 0]
[9 2 7]
[3 5 8]
[8 5 3]


In [199]:
for i in range (len(test)):
    print(test[i])

[4 7 0]
[9 2 7]
[3 5 8]
[8 5 3]


In [200]:
test2 = test**2
test2

array([[16, 49,  0],
       [81,  4, 49],
       [ 9, 25, 64],
       [64, 25,  9]], dtype=int32)

In [201]:
for i, j in zip(test,test2):
    print(i,'+',j,'=',i+j)

[4 7 0] + [16 49  0] = [20 56  0]
[9 2 7] + [81  4 49] = [90  6 56]
[3 5 8] + [ 9 25 64] = [12 30 72]
[8 5 3] + [64 25  9] = [72 30 12]


In [205]:
r= np.arange(0,36)
r.resize(6,6)
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [206]:
r[[2,3],[2,3]]

array([14, 21])

In [209]:
r[2::2,2::2]

array([[14, 16],
       [26, 28]])

In [210]:
r[::2,::2]

array([[ 0,  2,  4],
       [12, 14, 16],
       [24, 26, 28]])

In [211]:
r[2:4,2:4]


array([[14, 15],
       [20, 21]])